"""
Django settings for easystay project.

Generated by 'django-admin startproject' using Django 5.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-n9k&3z(hij^%i)4uk79*=nf%(xaj)2%&ux)xx#sy44^ft6oyk9'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'jazzmin',

    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Custom Apps
    'hotel',
    'addon',
    'user_dashboard',
    'userauths',

    # Third Party Apps
    'import_export',
    'crispy_forms',
    'mathfilters',
    'ckeditor_uploader',
    'django_ckeditor_5',
    'anymail',
    'taggit',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'easystay.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'easystay.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

JAZZMIN_SETTINGS = {
    # ---------- Branding ----------
    "site_title":  "Admin Panel",
    "site_header": "EasyStay",
    "site_brand":  "EasyStay",
    #"site_logo":   "hotel/img/logo.png",   # static/hotel/img/logo.png
    #"login_logo":  "hotel/img/logo_login.png",   # optional
    #"site_logo_classes": "img-circle",
    #"site_icon":  "hotel/img/favicon.png",  # 32×32 favicon
    "welcome_sign": "Welcome to EasyStay Admin Panel",
    "copyright":  "© 2025 EasyStay",

    # ---------- Global Search ----------
    "search_model": ["accounts.User", "booking.Reservation", "hotel.Room"],

    # if your User model has an avatar/url field set it here
    "user_avatar": None,

    # ---------- Top Menu ----------
    "topmenu_links": [
        {"name": "Dashboard", "url": "admin:index", "permissions": ["accounts.view_user"]},
        {"app":  "booking"},          # dropdown with all booking models
        {"app":  "hotel"},            # dropdown with room & hotel models
        {"app":  "payments"},
        {"name": "Docs", "url": "https://grandstay.readthedocs.io", "new_window": True},
    ],

    # ---------- User Menu ----------
    "usermenu_links": [
        {"model": "accounts.user"},
        {"name": "Support", "url": "mailto:support@grandstay.com"},
    ],

    # ---------- Sidebar ----------
    "show_sidebar": True,
    "navigation_expanded": True,
    "hide_apps": ["sessions"],        # hide if you like
    "hide_models": [],
    "order_with_respect_to": [
        "dashboard",                  # custom dashboard app first
        "booking",
        "booking.reservation",
        "hotel",
        "hotel.room",
        "payments",
        "accounts",
    ],

    # Custom quick links under specific apps
    "custom_links": {
        "booking": [
            {
                "name": "Bulk Check-in",
                "url":  "bulk_checkin",          # admin view name
                "icon": "fas fa-calendar-check",
                "permissions": ["booking.change_reservation"],
            }
        ],
    },

    # ---------- Icons ----------
    "icons": {
        "booking": "fas fa-concierge-bell",
        "booking.reservation": "fas fa-book",
        "hotel": "fas fa-hotel",
        "hotel.room": "fas fa-door-open",
        "payments": "fas fa-credit-card",
        "accounts": "fas fa-users-cog",
        "accounts.user": "fas fa-user",
    },
    "default_icon_parents":  "fas fa-chevron-circle-right",
    "default_icon_children": "fas fa-circle",

    # ---------- Related Modal ----------
    "related_modal_active": True,

    # ---------- UI Tweaks ----------
    "custom_css": "hotel/css/admin_custom.css",   # optional
    "custom_js":  "hotel/js/admin_custom.js",
    "use_google_fonts_cdn": True,
    "show_ui_builder": False,

    # ---------- Change Form ----------
    "changeform_format": "horizontal_tabs",         # keep default
    "changeform_format_overrides": {
        "booking.reservation": "collapsible",
        "hotel.room": "vertical_tabs",
    },

    # ---------- Internationalisation ----------
    "language_chooser": True,
}
